version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    volumes:
      - .:/flask_app.py